CREATE FUNCTION PROMEDIOPRODUCTO(@ID_PRODUCTO INT)
RETURNS INT
AS
BEGIN
DECLARE @PRECIO FLOAT
SELECT @PRECIO = SUM(PRECIO) FROM Factura_Detalles WHERE PRODUCTO = @ID_PRODUCTO
DECLARE @CANTIDAD INT
SELECT @CANTIDAD = COUNT(*) FROM Factura_Detalles WHERE PRODUCTO = @ID_PRODUCTO
DECLARE @PROMEDIO FLOAT
SET @PROMEDIO = (@PRECIO / @CANTIDAD)
RETURN @PROMEDIO
END