CREATE TABLE Productos
(
ID_PRODUCTO int NOT NULL PRIMARY KEY,
DESCRIPCION varchar(30) NOT NULL,
PRECIO_COSTO float,
PVP float
)

INSERT INTO Productos (ID_PRODUCTO, DESCRIPCION, PRECIO_COSTO)
VALUES
(
1,'SKATE',2340
),
(
2,'PELOTA DE FUTBOL',850.50
),
(
3,'PELOTA DE RUGBY',780.30
),
(
4,'BOTELLA RUNNER',450
),
(
5,'BOTINES NIKE MERCURIAL',3300
),
(
6,'CAMISETA SEL. ARGENTINA',1920.50
)

CREATE FUNCTION CALCULARPVP(@COSTO FLOAT)
RETURNS FLOAT
BEGIN
DECLARE @PVP FLOAT
SET @PVP = (@COSTO * 1.25) + 2
RETURN @PVP
END

UPDATE PRODUCTOS SET PVP = DBO.CALCULARPVP(PRECIO_COSTO)

CREATE TABLE Factura_Cabecera
(
ID int NOT NULL PRIMARY KEY,
SUBTOTAL float NOT NULL,
TOTAL_IMPORTE float NOT NULL
)

CREATE TABLE Factura_Detalles
(
ID int NOT NULL PRIMARY KEY,
FACTURA_CABECERA int NOT NULL FOREIGN KEY REFERENCES Factura_Cabecera(ID),
PRODUCTO int NOT NULL FOREIGN KEY REFERENCES Productos(ID_PRODUCTO),
PRECIO float NOT NULL
)

INSERT INTO Factura_Cabecera
VALUES
(
1,5000,0
),
(
2,1200,0
),
(
3,4100,0
),
(
4,1390,0
),
(
5,2000,0
)

INSERT INTO Factura_Detalles
VALUES
(
1,1,1,5000
),
(
2,2,1,1200
),
(
3,3,1,4100
),
(
4,4,1,1390
),
(
5,5,2,2000
)

UPDATE Factura_Cabecera
SET TOTAL_IMPORTE = (SUBTOTAL * 1.21)

SELECT dbo.[PROMEDIOPRODUCTO](1)