CREATE PROCEDURE INSERTARCABECERA
@CLIENTE INT, @TIPO_COMPROBANTE INT
AS
BEGIN  
DECLARE @ULTIMOCOMPROBANTE INT
SELECT @ULTIMOCOMPROBANTE = MAX(PUNTERO) FROM Tipos_Comprobantes WHERE ID = @TIPO_COMPROBANTE
SET @ULTIMOCOMPROBANTE = @ULTIMOCOMPROBANTE + 1
UPDATE Tipos_Comprobantes SET PUNTERO = @ULTIMOCOMPROBANTE WHERE ID = @TIPO_COMPROBANTE
INSERT INTO Comprobantes_Cabecera VALUES(@TIPO_COMPROBANTE, @CLIENTE, GETDATE(), 0, @ULTIMOCOMPROBANTE)
END
