CREATE PROCEDURE REPORTEVENTAS
@DIAS INT
AS
BEGIN
DECLARE CURSORCLIENTES CURSOR FOR SELECT DENOMINACION, IDENTIFICACION_CUIT_CUIL FROM Clientes
OPEN CURSORCLIENTES
DECLARE @NOMBRE VARCHAR(100)
DECLARE @IDENTIFICACION VARCHAR(100)
DECLARE @ID INT
DECLARE @CANTIDAD INT
DECLARE @CONTADOR INT
DECLARE @TOTALVENTAS FLOAT
SELECT @CANTIDAD = COUNT(*) FROM Clientes
SET @CONTADOR = 1
PRINT @CANTIDAD
WHILE (@CONTADOR <= @CANTIDAD)
BEGIN
FETCH CURSORCLIENTES INTO @ID, @NOMBRE, @IDENTIFICACION --IMPRIMO LOS SIGUIENTES REGISTROS--
SELECT @TOTALVENTAS = dbo.TOTALVENTAS(@ID, @DIAS)
PRINT 'NOMBRE: ' + @NOMBRE
PRINT 'IDENTIFICACION: ' + @IDENTIFICACION
PRINT 'VENTAS'
PRINT @TOTALVENTAS
PRINT '------'
SET @CONTADOR = @CONTADOR + 1
END
CLOSE CURSORCLIENTES
DEALLOCATE CURSORCLIENTES
END