CREATE FUNCTION TOTALVENTAS
(@IDCLIENTE INT, @DIAS INT)
RETURNS FLOAT
AS
BEGIN
DECLARE @TOTAL FLOAT
SELECT @TOTAL = SUM(SUBTOTAL) FROM Comprobantes_Detalles CD
INNER JOIN Comprobantes_Cabecera CC
ON CD.COMPROBANTE_CABECERA = CC.ID
WHERE CC.CLIENTE = @IDCLIENTE
AND CC.FECHA > GETDATE() - @DIAS
RETURN ISNULL(@TOTAL, 0)
END