BEGIN TRY
BEGIN TRAN
	INSERT INTO Clientes
	VALUES
	(
	'FERNANDEZ ALVAREZ JOSEFINA', 12653248, 'URUGUAY 433', 28
	)
	PRINT 'Inserción completada'
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
	PRINT 'Inserción fallida'
END CATCH